### ISSUE TITLE
Rate exceeded Error

### ISSUE THREAD

**Issue by n0ts** [kumogata/kumogata2#16]
kumogata2 cli gets error.

```
$ kumogata2 update foo.rb foo
[ERROR] Rate exceeded
lib/kumogata2/client.rb:602:in `map`
```

@winebarrel Is there any solution idea? ;)

**Comment by winebarrel** [comment]
How about passing `:retry_limit` as an option?

**Comment by n0ts** [comment]
> How about passing :retry_limit as an option?

Thanks! It's seems working!
I'll fix it!
